openapi: 3.0.0
info: 
  title: User API
  description: API to manage users
  version: "1.0.0"
servers: 
  - url: http://localhost:3000
paths: 
  /users:
    get:
      summary: Get a list of users
      description: Retrieves a list of users, optionally filtered users
      parameters: 
        - in: query
          name: name
          schema: 
            type: string
          required: false
          desciption: Name filter for user lookup
      respones:
        '200':
          description: A list of users
          content: 
            application/json: 
              schema:
                type: array
                items:
                  $ref: "#/components/schema/User"
components:
  schema:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "The umique identifier of the user"
        name: 
          type: string
          description: "The name of the user"
      required:
        - id
        - name