services:
  postgresdb:
    image: "postgres"
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD="password"
  backend:
    build: .
    image: "backend"
    container_name: "express_backend"
    ports:
      - 3000:3000
    depends_on:
      - postgresdb
    environment:
      - DATABASE_URL="postgresql://postgres:password@postgresdb:5432/postgres?schema=docker"